# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.33.10"


  config.ssh.forward_agent = true

  config.vm.synced_folder"~/fyp", "/home/vagrant/fyp", :nfs => true


  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--cpus", "2"]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
     vb.name = "Net Sec VM"

  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo locale-gen en_IE.UTF-8
    sudo apt-get update
    sudo apt-add-repository -y ppa:ansible/ansible
    sudo apt-get update
    sudo apt-get -y install ansible
    sudo apt-get -y autoremove
  SHELL
  
end
